remove explicit iter loops
lapce/lapce pull request #1867
Opened 2022-12-27 21:50 UTC by danieleades

2022-12-28 05:15 UTC, panekj commented
Does this have any meaningful impact such as improved performance or is it only a cosmetic change?

2022-12-28 07:01 UTC, danieleades commented
> Does this have any meaningful impact such as improved performance or is it only a cosmetic change?

it's cosmetic. Additionally, there's inherent value in suppressing/addressing things clippy complains about because it makes the linting less noisy, more likely to be used, and therefore more able to generate actual value. I would personally argue that's valuable enough in it's own right, though compared to #1871, this clippy 'noise' is at `clippy::pedantic` level, rather than `clippy::all`, so it's a slightly harder case to make.

2022-12-28 07:25 UTC, JustForFun88 commented
It seems to me that the changes only increase the compilation time, since now the compiler still has to infer the call to these `iter` and `iter_mut` functions itself.

2022-12-28 07:27 UTC, danieleades commented
> It seems to me that the changes only increase the compilation time, since now the compiler still has to infer the call to these `iter` and `iter_mut` functions itself.

Have you done some measurement that shows this? I would find an increase in compilation time here to be *very* surprising

2022-12-28 08:00 UTC, JustForFun88 commented
> Have you done some measurement that shows this? I would find an increase in compilation time here to be _very_ surprising

Yes, my mistake, you are right 😊. Looks like the `for` loop always results in an implicit call to `IntoIterator`, so both constructs are compile-time equivalent.

2022-12-29 12:31 UTC, Arjun31415 commented on lapce-core/src/syntax/util.rs
> +    for (_, pair_count) in &count {
I believe you need to use `count.values()`

2022-12-30 15:29 UTC, Arjun31415 approved these changes

2022-12-30 15:34 UTC, panekj requested changes
waiting for next clippy version

2023-07-18 17:17 UTC, panekj commented
Closing since those lints don't seem to be default anytime soon

2023-07-18 17:17 UTC, closed without merging