Fix unicode path handling on windows LSPs
lapce/lapce pull request #2921
Opened 2024-01-15 14:06 UTC by thistle-witch

Closes #2920 

Tested with Rust analyzer. `to_file_path()` properly converts `file:///c:/...` style URIs into properly drive rooted windows paths.

2024-01-15 14:23 UTC, panekj requested changes
This breaks lapce

2024-01-15 14:25 UTC, thistle-witch commented
I'm not sure what you mean by "this breaks lapce"? I tested against the relevant URLs. The handling seemed to be specific to windows file URIs which I tested. No other code was affected.

2024-01-15 14:26 UTC, panekj commented
Using `to_file_path()` makes lapce stack overflow

2024-01-15 14:26 UTC, thistle-witch commented
I'm curious how you got that result. I ran a build of this myself.

2024-01-15 14:32 UTC, thistle-witch commented
If you have a test project or example URI that causes the stack overflow I can try to find out what is going on.

2024-01-15 14:34 UTC, panekj commented
The test code is what `cargo init` gives, typing and deleting `println!` causes overflow but it doesn't happen in release mode

2024-01-15 14:38 UTC, thistle-witch commented
It would be helpful if you could provide the exact URI that is causing this issue for you. I have just run a debug build with a `cargo init` project and do not get the same results at all. To confirm, which version of windows are you using? Its entirely possible this stack overflow is caused by stack size differences.

2024-05-29 20:57 UTC, panekj commented
Fixed via f2355aa0b8839aacc5fa684db2c8b75b5258e251

2024-05-29 20:57 UTC, closed without merging